Uspelite.Web/Controllers/CategoriesController.cs
namespace Uspelite.Web.Controllers
{
    using System.Web.Mvc;
    using System.Linq;
    using Infrastructure.Mapping.Contracts;
    using Models.Categories;
    using Services.Data.Contracts;

    public class CategoriesController : BaseController
    {
        private readonly ICategoriesService categoriesService;

        public CategoriesController(ICategoriesService categoriesService)
        {
            this.categoriesService = categoriesService;
        }

        public ActionResult Show(string slug, int page = 1, int pageSize = 10)
        {
            var model = this.categoriesService.GetPaged(slug, page, pageSize).To<PageableCategoryArticlesViewModel>().FirstOrDefault();

            if(model == null)
            {
                return this.HttpNotFound();
            }

            model.Slug = slug;
            model.PageSize = pageSize;

            if (page <= 6)
            {
                model.DisplayPageFrom = 1;
                model.DisplayPageTo = 10 > model.TotalPages ? model.TotalPages : 10;
            }
            else if(page > 6)
            {
                var displayTo = page + 4;
                model.DisplayPageTo = model.TotalPages <= displayTo? model.TotalPages : displayTo;
                model.DisplayPageFrom = model.DisplayPageTo - 9;
            }

            return this.View(model);
        }
    }
}

Uspelite.Web/Controllers/SearchController.cs
namespace Uspelite.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    using Infrastructure.Mapping.Contracts;
    using Models.Articles;
    using Services.Data.Contracts;
    using System.Linq;
    using System.Web.Routing;
    using Models.Home;

    public class SearchController : BaseController
    {
        private readonly IArticlesService articlesService;

        public SearchController(IArticlesService articlesService)
        {
            this.articlesService = articlesService;
        }

        public ActionResult Articles(string query, int page = 1, int pageSize = 10)
        {
            var itemsToSkip = (page - 1) * pageSize;

            var foundItemsDTO = this.articlesService.FullTextSearch(query, page, pageSize);

            var foundItems = foundItemsDTO
                .ResultsInTitles
                .Skip(itemsToSkip)
                .Take(pageSize)
                .Select(x => x.Item)
                .To<ArticleViewModel>()
                .ToList();

            var foundItemsCount = foundItems.Count;
            if (foundItemsCount < pageSize)
            {
                foundItems.AddRange(foundItemsDTO
                                        .ResultsInContents
                                        .OrderByDescending(x => x.Hits)
                                        .Skip(itemsToSkip)
                                        .Take(pageSize - foundItems.Count)
                                        .Select(x => x.Item)
                                        .To<ArticleViewModel>()
                                        .ToList());
            }


            var model = new HomeIndexViewModel
                {
                    SearchResults = foundItems,
                    NewestPostsAndCategories = null,
                    HighRatedPosts = null,
                    MostCommentedPosts = null,
                    HighRatedInCategory = null,
                    TopArticle = null,
                    IsSearchResult = true
                };

            model.Query = query;
            model.AllItemsCount = foundItemsDTO.AllSearchedResultsCount;
            model.TotalPages = (int) Math.Ceiling(model.AllItemsCount / (decimal) pageSize);
            model.PageSize = pageSize;
            model.CurrentPage = page;

            if (page <= 6)
            {
                model.DisplayPageFrom = 1;
                model.DisplayPageTo = 10 > model.TotalPages ? model.TotalPages : 10;
            }
            else if (page > 6)
            {
                var displayTo = page + 4;
                model.DisplayPageTo = model.TotalPages <= displayTo ? model.TotalPages : displayTo;
                model.DisplayPageFrom = model.DisplayPageTo - 9;
            }

            return this.View("~/Views/Home/Index.cshtml", model);
        }
    }
}

Uspelite.Web/Views/Shared/Partials/_Footer.cshtml
<footer id="page-footer" class="site-footer">
    <div class="container">
        <nav id="foot-menu" class="hidden-xs">
            <ul class="clearfix">
                @*<li class="home current"><a href="#"><span class="glyphicon glyphicon-home"></span></a></li>
                <li class="cat-news"><a href="#">News</a></li>
                <li class="cat-sports"><a href="#">Sports</a></li>
                <li class="cat-lifestyle"><a href="#">Lifestyle</a></li>
                <li class="cat-showtime"><a href="#">Showtime</a></li>
                <li class="cat-tech"><a href="#">Tech</a></li>
                <li class="cat-business"><a href="#">Business</a></li>
                <li class="cat-extra"><a href="#">Extra +</a></li>
                <li class="options"><a href="#" class="scrollToTop">Back to top <span class="glyphicon glyphicon-chevron-up"></span></a></li>*@
            </ul>
        </nav>
        <div class="about row">
            <div class="col-sm-12 col-md-3">
                <h3>
                    <a href="#"><img src="~/Content/Pics/UspeliteLionWhite2.png" alt="младите успели българи лого"></a>
                </h3>
            </div>
            <div class="col-sm-6 col-md-5">
                <h4>За нас</h4>
                <p>Aliquam erat volutpat. Aliquam porta nibh id odio ornare ullamcorper. Etiam sit amet consectetur arcu. Suspendisse dolor nisl, eleifend quis metus a, sollicitudin semper orci.</p>
                <a href="#"><i class="fa fa-twitter fa-lg"></i></a>
                <a href="#"><i class="fa fa-facebook-square fa-lg"></i></a>
                <a href="#"><i class="fa fa-linkedin-square fa-lg"></i></a>
                <a href="#"><i class="fa fa-google-plus-square fa-lg"></i></a>
                <a href="#"><i class="fa fa-vimeo-square fa-lg"></i></a>
                <a href="#"><i class="fa fa-youtube fa-lg"></i></a>
            </div>
            <div class="col-sm-6 col-md-4">
                <h4>Additional information</h4>
                <ul>
                    <li><a href="#">About us</a></li>
                    <li><a href="#">Legal agreement</a></li>
                    <li><a href="#">Our staff</a></li>
                    <li><a href="#">Privacy policy</a></li>
                    <li><a href="#">Contact us</a></li>
                    <li><a href="#">Terms of Service</a></li>
                    <li><a href="#">Become a member</a></li>
                    <li><a href="#">Press Releases</a></li>
                </ul>
            </div>
        </div>
        <div class="copyright row">
            <div class="col-sm-6">
                © <a href="#">Младите успели българи</a> @DateTime.Now.Year All rights reserved.
            </div>
        </div>
    </div>
</footer>

Uspelite.Web/Views/Shared/Partials/_Header.cshtml
@using Uspelite.Data.Common.Roles


<header id="page-header-mobile" class="visible-xs">
    @(Html.Action<ChildActionsController>(x => x.GetMobileClientNavigation()))
</header>


<div class="top-nav"> 
	<div class="container">
		<nav class="top">
			<ul class="inline">
				<li class="topnav"><a href="/">ИНИЦИАТИВИ</a></li>
				<li class="topnav"><a href="/">ВЪЗМОЖНОСТИ</a></li>
			    <li class="topnav">@(Html.ActionLink<HomeController>("КОИ СМЕ НИЕ?", x => x.About()))</li>
				<li class="topnav"><a href="/">ПАРТНЬОРИ</a></li>
			</ul>
			<div class="login">
			    @Html.Partial("~/Views/Shared/_LoginPartial.cshtml")
			</div>
		</nav>
	</div>
</div>

<header id="page-header" class="hidden-xs">
    <div id="header-branding">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-md-4">
                    <h1>
                        <a href="/"><img id="logo-img" src="~/Content/Pics/UspeliteLogoNew.png" alt="uspelite"></a> 
                        <span class="heading cuprum-regular">Успелите.БГ</span>
                    </h1>
                </div>
		<div class="col-sm-6 col-md-4 col-md-offset-4">
		
		
                    @using (Html.BeginForm("Articles", "Search", FormMethod.Get, new {id = "search-form"}))
                    {
                                <form id="search-form" name="search-form">
                                        <input name="query" placeholder="Търсете..." type="text" />
                                            <button type="submit"><span class="glyphicon glyphicon-search"></span></button>
                                </form>
                    }
                   </div>
		</div>
            </div>
        </div>

    <div id="header-navigation">
        @(Html.Action<ChildActionsController>(x => x.GetClientNavigation()))
    </div>

</header>

Uspelite.Web/Views/Shared/Partials/_PageSlider.cshtml
<div id="page-slider" class="slider-layout-1 clearfix">

    <!-- start:container -->
    <div class="container">

        <!-- start:carousel -->
        <div class="caroufredsel_wrapper" style="display: block; text-align: start; float: none; position: relative; top: auto; right: auto; bottom: auto; left: auto; z-index: auto; width: 1170px; height: 452px; margin: 0px; overflow: hidden; cursor: move;">
            <div id="slider-carousel" style="text-align: left; float: none; position: absolute; top: 0px; right: auto; bottom: auto; left: 0px; margin: 0px; width: 8190px; height: 452px;">

                <!-- start:row -->
                <div class="row" style="width: 1200px;">

                    <!-- start:col -->
                    <div class="col-sm-8">

                        <article class="linkbox large has-meta cat-sports">
                            <a href="#">
                                <img src="~/Content/Theme/images/dummy/819x452.jpg" width="819" height="452" alt="Responsive image" class="img-responsive">
                                <div class="overlay">
                                    <h2>Jimenez signing keeps O's in contention</h2>
                                    <p>The concern within the Baltimore Orioles’ organization, as the negotiations with Ubaldo Jimenez began percolating over the last 48 hours, was that the Boston Red Sox or Toronto Blue Jays would snag...</p>
                                </div>
                            </a>
                            <a href="#" class="theme">
                                Sport
                            </a>
                            <div class="postmeta">
                                <span class="fa-calendar" itemprop="dateCreated">Nov 12th, 2015</span>
                                <span class="fa-comments"><a href="#">15</a></span>
                                <span class="icon fa-eye">471</span>
                            </div>
                        </article>

                    </div>
                    <!-- end:col -->
                    <!-- start:col -->
                    <div class="col-sm-4">

                        <article class="linkbox has-meta cat-sports">
                            <a href="#">
                                <img src="~/Content/Theme/images/dummy/350x150.jpg" width="560" height="390" alt="Responsive image" class="img-responsive">
                                <div class="overlay">
                                    <h3>Levy wins first European Tour title in China</h3>
                                </div>
                            </a>
                            <a href="#" class="theme">
                                Sport
                            </a>
                            <div class="postmeta">
                                <span class="fa-calendar" itemprop="dateCreated">Nov 12th, 2015</span>
                                <span class="fa-comments"><a href="#">15</a></span>
                                <span class="icon fa-eye">471</span>
                            </div>
                        </article>

                        <article class="linkbox has-meta cat-sports">
                            <a href="#">
                                <img src="~/Content/Theme/images/dummy/350x150.jpg" width="560" height="390" alt="Responsive image" class="img-responsive">
                                <div class="overlay">
                                    <h3>Barkley and Shaq speak on on Donald Sterling</h3>
                                </div>
                            </a>
                            <a href="#" class="theme">
                                Sport
                            </a>
                            <div class="postmeta">
                                <span class="fa-calendar" itemprop="dateCreated">Nov 12th, 2015</span>
                                <span class="fa-comments"><a href="#">15</a></span>
                                <span class="icon fa-eye">471</span>
                            </div>
                        </article>

                        <article class="linkbox has-meta cat-sports">
                            <a href="#">
                                <img src="~/Content/Theme/images/dummy/350x150.jpg" width="560" height="390" alt="Responsive image" class="img-responsive">
                                <div class="overlay">
                                    <h3>Ranking the top 100 prospects in the NFL draft</h3>
                                </div>
                            </a>
                            <a href="#" class="theme">
                                Sport
                            </a>
                            <div class="postmeta">
                                <span class="fa-calendar" itemprop="dateCreated">Nov 12th, 2015</span>
                                <span class="fa-comments"><a href="#">15</a></span>
                                <span class="icon fa-eye">471</span>
                            </div>
                        </article>

                    </div>
                    <!-- end:col -->

                </div>
                <!-- end:row -->
                <!-- start:row -->
                <div class="row" style="width: 1200px;">

                    <!-- start:col -->
                    <div class="col-sm-8">

                        <article class="linkbox large cat-news">
                            <a href="#">
                                <img src="~/Content/Theme/images/dummy/819x452.jpg" width="819" height="452" alt="Responsive image" class="img-responsive">
                                <div class="overlay">
                                    <h2>Jimenez signing keeps O's in contention</h2>
                                    <p>The concern within the Baltimore Orioles’ organization, as the negotiations with Ubaldo Jimenez began percolating over the last 48 hours, was that the Boston Red Sox or Toronto Blue Jays would snag...</p>
                                </div>
                            </a>
                            <a href="#" class="theme">
                                News
                            </a>
                        </article>

                    </div>
                    <!-- end:col -->
                    <!-- start:col -->
                    <div class="col-sm-4">

                        <article class="linkbox cat-news">
                            <a href="#">
                                <img src="~/Content/Theme/images/dummy/350x150.jpg" width="560" height="390" alt="Responsive image" class="img-responsive">
                                <div class="overlay">
                                    <h3>Levy wins first European Tour title in China</h3>
                                </div>
                            </a>
                            <a href="#" class="theme">
                                News
                            </a>
                        </article>

                        <article class="linkbox cat-news">
                            <a href="#">
                                <img src="~/Content/Theme/images/dummy/350x150.jpg" width="560" height="390" alt="Responsive image" class="img-responsive">
                                <div class="overlay">
                                    <h3>Barkley and Shaq speak on on Donald Sterling</h3>
                                </div>
                            </a>
                            <a href="#" class="theme">
                                News
                            </a>
                        </article>

                        <article class="linkbox cat-news">
                            <a href="#">
                                <img src="~/Content/Theme/images/dummy/350x150.jpg" width="560" height="390" alt="Responsive image" class="img-responsive">
                                <div class="overlay">
                                    <h3>Ranking the top 100 prospects in the NFL draft</h3>
                                </div>
                            </a>
                            <a href="#" class="theme">
                                News
                            </a>
                        </article>

                    </div>
                    <!-- end:col -->

                </div>
                <!-- end:row -->
                <!-- start:row -->
                <div class="row" style="width: 1200px;">

                    <!-- start:col -->
                    <div class="col-sm-8">

                        <article class="linkbox large cat-showtime">
                            <a href="#">
                                <img src="~/Content/Theme/images/dummy/819x452.jpg" width="819" height="452" alt="Responsive image" class="img-responsive">
                                <div class="overlay">
                                    <h2>Jimenez signing keeps O's in contention</h2>
                                    <p>The concern within the Baltimore Orioles’ organization, as the negotiations with Ubaldo Jimenez began percolating over the last 48 hours, was that the Boston Red Sox or Toronto Blue Jays would snag...</p>
                                </div>
                            </a>
                            <a href="#" class="theme">
                                Showtime
                            </a>
                        </article>

                    </div>
                    <!-- end:col -->
                    <!-- start:col -->
                    <div class="col-sm-4">

                        <article class="linkbox cat-showtime">
                            <a href="#">
                                <img src="~/Content/Theme/images/dummy/350x150.jpg" width="560" height="390" alt="Responsive image" class="img-responsive">
                                <div class="overlay">
                                    <h3>Levy wins first European Tour title in China</h3>
                                </div>
                            </a>
                            <a href="#" class="theme">
                                Showtime
                            </a>
                        </article>

                        <article class="linkbox cat-showtime">
                            <a href="#">
                                <img src="~/Content/Theme/images/dummy/350x150.jpg" width="560" height="390" alt="Responsive image" class="img-responsive">
                                <div class="overlay">
                                    <h3>Barkley and Shaq speak on on Donald Sterling</h3>
                                </div>
                            </a>
                            <a href="#" class="theme">
                                Showtime
                            </a>
                        </article>

                        <article class="linkbox cat-showtime">
                            <a href="#">
                                <img src="~/Content/Theme/images/dummy/350x150.jpg" width="560" height="390" alt="Responsive image" class="img-responsive">
                                <div class="overlay">
                                    <h3>Ranking the top 100 prospects in the NFL draft</h3>
                                </div>
                            </a>
                            <a href="#" class="theme">
                                Showtime
                            </a>
                        </article>

                    </div>
                    <!-- end:col -->

                </div>
                <!-- end:row -->


            </div>
        </div>
        <!-- end:slider-carousel -->
        <!-- start:slider-nav -->
        <div class="slider-nav">
            <a id="slider-prev" class="prev" href="#" style="display: block;"><i class="fa fa-chevron-left"></i></a>
            <a id="slider-next" class="next" href="#" style="display: block;"><i class="fa fa-chevron-right"></i></a>
        </div>
        <!-- end:slider-nav -->
    </div>
    <!-- end:container -->

</div>

Uspelite.Web/Views/Shared/Partials/_Pagination.cshtml
<nav>
    <ul class="pagination">
        @if (Model.CurrentPage != 1)
            {
            <li>
                <a href="/Categories/Show?slug=@Model.Slug&page=@(Model.CurrentPage - 1)&pageSize=@Model.PageSize" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        }
        @for (int i = Model.DisplayPageFrom; i <= Model.DisplayPageTo; i++)
            {
                var className = string.Empty;
                if (Model.CurrentPage == i)
                {
                    className = "active";
                }
                <li class="@className">@Html.ActionLink(i.ToString(), "Show", "Categories", new { slug = Model.Slug, page = i, pageSize = Model.PageSize }, null)</li>
        }
        @if (Model.DisplayPageTo != Model.TotalPages)
            {
            <li>
                <a href="/Categories/Show?slug=@Model.Slug&page=@(Model.CurrentPage + 1)&pageSize=@Model.PageSize" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        }

    </ul>
</nav>

Uspelite.Web/Views/Shared/Partials/_RatingStars.cshtml
@model Uspelite.Web.Models.Common.IRateable

<div class="rating-container">
    <div class="review-rating">
        <ul class="rating" data-currentRating="@Model.Rating" data-Id="@Model.Id" data-rateType="@Model.RateType">
            @for (int j = 0; j < 5; j++)
            {
                if (Model.Rating > j)
                {
                    <li class="li-rated"></li>
                }
                else
                {
                    <li></li>
                }
            }
        </ul>
        <div class="alert alert-success rate-message" style="display: none;"></div>
    </div>
</div>