Uspelite.Web/Models/ImageViewModel.cs
namespace Uspelite.Web.Models
{
    using System;
    using System.Linq.Expressions;
    using AutoMapper;
    using Data.Models;
    using Infrastructure.Mapping.Contracts;
    using Services.Common;

    public class ImageViewModel : IMapFrom<Image>, IMapTo<Image>, IHaveCustomMappings
    {
        public static Expression<Func<Image, ImageViewModel>> FromModel
        {
            get
            { 
                return x => new ImageViewModel
                    {
                        IsMain = x.IsMain, 
                        Title = x.Title,
                        Resized400Picture = x.PathResizedImage
                };
            }
        }

        public string Title { get; set; }

        public string Resized400Picture { get; set; }

        public string OriginalSizedPicture { get; set; }

        public bool IsMain { get; set; }

        public void CreateMappings(IMapperConfiguration configuration)
        {
            configuration.CreateMap<Image, ImageViewModel>()
                         .ForMember(x => x.Resized400Picture, opt => opt.MapFrom(x => Constants.IMAGES_PREFIX_FROM_ROOT + x.PathResizedImage))
                         .ForMember(x => x.OriginalSizedPicture, opt => opt.MapFrom(x => Constants.IMAGES_PREFIX_FROM_ROOT + x.PathOriginalSize));
        }
    }
}

Uspelite.Web/Models/Images/ImageViewModel.cs
namespace Uspelite.Web.Models.Images
{
    using System.Linq;
    using AutoMapper;
    using Common;
    using Data.Models;
    using Infrastructure.Mapping.Contracts;
    using Services.Common;

    public class ImageViewModel : IRateable, IMapFrom<Image>, IHaveCustomMappings
    {
        public int Id { get; set; }

        public int RateType { get { return (int) RateableType.Image; } }

        public int Rating { get; set; }

        public string Title { get; set; }

        public string Resized400Picture { get; set; }

        public string OriginalSizedPicture { get; set; }

        public bool IsMain { get; set; }

        public void CreateMappings(IMapperConfiguration configuration)
        {
            configuration.CreateMap<Image, ImageViewModel>()
                         .ForMember(x => x.Resized400Picture, opt => opt.MapFrom(x => Constants.IMAGES_PREFIX_FROM_ROOT + x.PathResizedImage))
                         .ForMember(x => x.OriginalSizedPicture, opt => opt.MapFrom(x => Constants.IMAGES_PREFIX_FROM_ROOT + x.PathOriginalSize))
                         .ForMember(x => x.Rating, opt => opt.MapFrom(x => x.Ratings.Any() ? (x.Ratings.Sum(y => y.Value) / x.Ratings.Count) : 0));
        }


    }
}

Uspelite.Web/Models/Images/PageableImageViewModel.cs
namespace Uspelite.Web.Models.Images
{
    using System.Collections.Generic;
    using Infrastructure.Mapping.Contracts;
    using Services.Data.DTO;

    public class PageableImageViewModel : IMapFrom<PagedImageDTO>
    {
        public IEnumerable<ImageViewModel> Images { get; set; }

        public int CurrentPage { get; set; }

        public int TotalPages { get; set; }

        public int AllItemsCount { get; set; }

        public int PageSize { get; set; }

        public int DisplayPageFrom { get; set; }

        public int DisplayPageTo { get; set; }
    }
}

Uspelite.Web/Controllers/ImagesController.cs
namespace Uspelite.Web.Controllers
{
    using System.Web.Mvc;
    using Models.Images;
    using Services.Data.Contracts;

    public class ImagesController : BaseController
    {
        private const int PAGE_SIZE = 32;

        private IImagesService imagesService;

        public ImagesController(IImagesService imagesService)
        {
            this.imagesService = imagesService;
        }

        [HttpGet]
        public ActionResult Gallery(int page = 1, int pageSize = PAGE_SIZE)
        {
            var dto = this.imagesService.AllPaged(page, pageSize);
            var model = this.Mapper.Map<PageableImageViewModel>(dto);

            model.PageSize = pageSize;

            if (page <= 6)
            {
                model.DisplayPageFrom = 1;
                model.DisplayPageTo = 10 > model.TotalPages ? model.TotalPages : 10;
            }
            else if (page > 6)
            {
                var displayTo = page + 4;
                model.DisplayPageTo = model.TotalPages <= displayTo ? model.TotalPages : displayTo;
                model.DisplayPageFrom = model.DisplayPageTo - 9;
            }
            return this.View(model);
        }
    }
}

Uspelite.Web/Views/Images/Gallery.cshtml
@model Uspelite.Web.Models.Images.PageableImageViewModel

@section sidebar{
    @(Html.Action<ChildActionsController>(x => x.GetSideBar()))
}
<article>
    <header>
        <h2>
            <a href="#">Галерия</a>
        </h2>
        <span class="borderline"></span>
    </header>

    <div id="filter-box"></div>
    <section>
        <div id="article-gallery" class="row">
            @foreach (var mod in Model.Images)
            {
                <div class="col-xs-6 col-sm-3 pic-holder">
                    <article class="clearfix">
                        <a href="/@mod.OriginalSizedPicture">
                            <img src="/@mod.Resized400Picture" alt="Responsive image" class="img-responsive">
                            <div class="zoomix">
                                <i class="fa fa-search"></i>
                            </div>
                        </a>
                    </article>
                    @Html.Partial("~/Views/Shared/Partials/_RatingStars.cshtml", mod)
                </div>
            }
        </div>

        <nav>
            <div class="text-center">
                <ul class="pagination">
                    @if (Model.CurrentPage != 1)
                    {
                        <li>
                            <a href="/Images/Gallery?page=@(Model.CurrentPage - 1)&pageSize=@Model.PageSize" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    }
                    @for (int i = Model.DisplayPageFrom; i <= Model.DisplayPageTo; i++)
                    {
                        var className = string.Empty;
                        if (Model.CurrentPage == i)
                        {
                            className = "active";
                        }
                        <li class="@className">@Html.ActionLink(i.ToString(), "Gallery", "Images", new {page = i, pageSize = Model.PageSize}, null)</li>
                    }
                    @if (Model.DisplayPageTo != Model.TotalPages)
                    {
                        <li>
                            <a href="/Images/Gallery?page=@(Model.CurrentPage + 1)&pageSize=@Model.PageSize" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    }
                </ul>
            </div>
        </nav>
    </section>
</article>

@section scripts {
    @Scripts.Render("~/Scripts/Custom/ratingScript.js")
}

@section overridingStyles {

    <style>
        div.pic-holder {
            margin-bottom:20px;
        }

         @@media ( min-width: 991px ) {
             img.img-responsive {
                 height : 112px;
             }
         }
        @@media ( min-width: 768px ) {
            img.img-responsive {
                width: 170px;
                height : 120px;
            }
        }
        @@media ( min-width: 430px ) {
            img.img-responsive {
                width: 200px;
                height : 150px;
            }
        }
    </style>
}