Uspelite.Web/Areas/Administration/Models/Crawlers/CrowlerViewModel.cs
namespace Uspelite.Web.Areas.Administration.Models.Crawlers
{
    using System.Collections.Generic;
    using Services.Data.DTO;

    public class CrowlerViewModel
    {
        public IEnumerable<CrowlerDTO> Crawlers { get; set; }
    }
}

Uspelite.Web/Areas/Administration/Controllers/CrowlersController.cs
namespace Uspelite.Web.Areas.Administration.Controllers
{
    using System.Linq;
    using System.Web.Mvc;
    using Models.Crawlers;
    using Services.Data.Crawl;
    using Microsoft.AspNet.Identity;

    public class CrowlersController : AdministratorController
    {
        const int PARSE_PORTION_COUNT = 30000;

        private readonly ICrawlService crawlNewsService;

        public CrowlersController(ICrawlService crawlNewsService)
        {
            this.crawlNewsService = crawlNewsService;
        }

        public ActionResult Index()
        {
            var model = new CrowlerViewModel();
            model.Crawlers = this.crawlNewsService.GetAllPossibilities().ToList();
            return this.View(model);
        }

        public ActionResult StartPopulation(string Crawlers)
        {
            this.crawlNewsService.UpdateCount(int.Parse(Crawlers));
            return this.View(int.Parse(Crawlers));
        }

        public void StartPopulate(string id)
        {
            var userId = this.User.Identity.GetUserId();
            this.crawlNewsService.UpdateCount(int.Parse(id), PARSE_PORTION_COUNT);
            this.crawlNewsService.ParseNews(int.Parse(id), userId, PARSE_PORTION_COUNT);
        }

        public ActionResult GetParsedNewsCount(string id)
        {
            var count = this.crawlNewsService.GetCount(int.Parse(id));

            if(this.Session["passedItems"] == null)
            {
                this.Session["passedItems"] = 0;
            }
            else
            {
                this.Session["passedItems"] = int.Parse(this.Session["passedItems"].ToString()) + 80;
            }


            var passedItems = this.Session["passedItems"].ToString();
            var result = string.Format("Successfully parsed : {0}    From : {1}", count, passedItems);

            return this.Content(result);
        }
    }
}

Uspelite.Web/Areas/Administration/Views/Crowlers/Index.cshtml
@model Uspelite.Web.Areas.Administration.Models.Crawlers.CrowlerViewModel

@using (Html.BeginForm("StartPopulation", "Crowlers", FormMethod.Post, new { id = "start-populating-form" }))
{
    @Html.LabelFor(x => x.Crawlers, new { @class = "col-lg-2 control-label" })
    @Html.DropDownListFor(x => x.Crawlers, new SelectList(Model.Crawlers, "Id", "Name", Model.Crawlers.FirstOrDefault()), new { @class = "btn btn-default dropdown-toggle" })

    <input type="submit" class="btn btn-warning"/>
}

Uspelite.Web/Areas/Administration/Views/Crowlers/StartPopulation.cshtml
@model Int32

<h1 id="title" data-model-id="@Model" >Population procedure started ...</h1>

<div id="loading-element" style="display:none">Loading...</div>
<span>Currently populated articles :</span> <span id="count-span"></span>
<div id="success"></div>

@section adminScripts {
    <script>
        function getAddMovieForm() {
            var id = $('#title').attr('data-model-id');
            $('#loading-element').html("Loading...");
            $('#count-span').load('/Administration/Crowlers/GetParsedNewsCount/' + id);
        }

        $(function () {
            var id = $('#title').attr('data-model-id');
            //var userId = $('#title').attr('data-user-id');
            $.post('/Administration/Crowlers/StartPopulate/', { id: id }, function (success) {
                $('#success').html('SUCCESS');
            });
        });

        setInterval(getAddMovieForm, 10000);
    </script>
}